d = {
    'deafening greed':[],
    'shrieking greed':[],
    'screaming greed':[],
    'wailing greed':[],
    'weeping greed':[],
    'muttering greed':[],
    'whispering greed':[],
    'deafening contempt':[],
    'shrieking contempt':[],
    'screaming contempt':[],
    'wailing contempt':[],
    'weeping contempt':[],
    'muttering contempt':[],
    'whispering contempt':[],
    'deafening hatred':[],
    'shrieking hatred':[],
    'screaming hatred':[],
    'wailing hatred':[],
    'weeping hatred':[],
    'muttering hatred':[],
    'whispering hatred ':[],
    'deafening woe':[],
    'shrieking woe':[],
    'screaming woe':[],
    'wailing woe':[],
    'weeping woe':[],
    'muttering woe':[],
    'whispering woe':[],
    'deafening fear':[],
    'shrieking fear':[],
    'screaming fear':[],
    'wailing fear':[],
    'weeping fear':[],
    'muttering fear':[],
    'deafening anger':[],
    'shrieking anger':[],
    'screaming anger':[],
    'wailing anger':[],
    'weeping anger':[],
    'muttering anger':[],
    'deafening torment':[],
    'shrieking torment':[],
    'screaming torment':[],
    'wailing torment':[],
    'weeping torment':[],
    'muttering torment':[],
    'deafening sorrow':[],
    'shrieking sorrow':[],
    'screaming sorrow':[],
    'wailing sorrow':[],
    'weeping sorrow':[],
    'muttering sorrow':[],
    'deafening rage':[],
    'shrieking rage':[],
    'screaming rage':[],
    'wailing rage':[],
    'weeping rage':[],
    'deafening suffering':[],
    'shrieking suffering':[],
    'screaming suffering':[],
    'wailing suffering':[],
    'weeping suffering':[],
    'deafening wrath':[],
    'shrieking wrath':[],
    'screaming wrath':[],
    'wailing wrath':[],
    'weeping wrath':[],
    'deafening doubt':[],
    'shrieking doubt':[],
    'screaming doubt':[],
    'wailing doubt':[],
    'weeping doubt':[],
    'deafening loathing':[],
    'shrieking loathing':[],
    'screaming loathing':[],
    'deafening zeal':[],
    'shrieking zeal':[],
    'screaming zeal':[],
    'wailing zeal':[],
    'deafening anguish':[],
    'shrieking anguish':[],
    'screaming anguish':[],
    'wailing anguish':[],
    'deafening spite':[],
    'shrieking spite':[],
    'screaming spite':[],
    'wailing spite':[],
    'deafening scorn':[],
    'shrieking scorn':[],
    'screaming scorn':[],
    'deafening envy':[],
    'shrieking envy':[],
    'screaming envy':[],
    'deafening misery':[],
    'shrieking misery':[],
    'screaming misery':[],
    'deafening dread':[],
    'shrieking dread':[],
    'screaming dread':[],
    'insanity':[],
    'horror':[],
    'delirium':[],
    'hysteria':[],
    'remnant':[],
}

print(list(d.keys())[1])